exclude: 'docs|node_modules|.git|.tox'
default_stages: [commit]
fail_fast: false

files: app/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml
      # - id: check-toml

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: ["--profile", "black"]

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.2
    hooks:
    - id: pycln
      args: ["--all", "true"]


  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      exclude: "^$__init__.py"

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: 
      - "--max-line-length=100"
      - "--extend-ignore=E203,E501"
  