# Generated by Django 4.1.2 on 2022-10-07 11:35

import django_resized.forms
import userauth.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="user.png",
                force_format="PNG",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[200, 200],
                upload_to=userauth.utils.upload_to,
            ),
        ),
    ]
