# Generated by Django 4.1.7 on 2023-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0005_remove_user_picture_object_name_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dominant_colors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
