# Generated by Django 4.1.2 on 2022-10-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_approbation_created_at_approbation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='primary_color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
