# Generated by Django 4.1.2 on 2022-10-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_publication_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='dominant_colors',
            field=models.JSONField(blank=True, default={'platform': 'web'}, null=True),
        ),
    ]
