# Generated by Django 4.1.2 on 2022-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_publication_dominant_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='dominant_colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
