# Generated by Django 4.1.2 on 2022-10-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_publication_dominant_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='dominant_colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
