# Generated by Django 4.1.7 on 2023-04-04 12:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("index", "0011_index_object_name_alter_publication_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=255)),
                (
                    "object_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dominant_colors", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("refused", "Refused"),
                        ],
                        default="pending",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_publications",
                        to="index.index",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
