services:
  postgres:
    image: postgres:14-bullseye
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    ports:
    - "127.0.0.1:5432:5432"

  redis:
    image: redis:7-bullseye
    command: ["--port", "6380"]
    ports:
    - "127.0.0.1:6380:6380"

  django:
    build:
      context: ./..
      dockerfile: ./docker-compose/Dockerfile
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    depends_on:
    - postgres
    env_file:
    - ../app/config/.env
    volumes:
    - ../app:/usr/local/src/app
    ports:
    - "127.0.0.1:8000:8000"


volumes:
  postgres_data: