# Generated by Django 4.1.2 on 2022-10-09 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approbation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name="index",
            old_name="created_by",
            new_name="creator",
        ),
        migrations.AddField(
            model_name="index",
            name="description",
            field=models.CharField(default="Description", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publication",
            name="description",
            field=models.CharField(default="Another one", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publication",
            name="name",
            field=models.CharField(default="name-one", max_length=63),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                fields=("name", "index"), name="unique_publication_index_name"
            ),
        ),
        migrations.AddField(
            model_name="approbation",
            name="proposition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approbations",
                to="core.proposition",
            ),
        ),
        migrations.AddField(
            model_name="approbation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approbations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
