# Generated by Django 4.1.2 on 2022-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poukidex", "0009_proposition_dominant_colors"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="approbation",
            constraint=models.UniqueConstraint(
                fields=("proposition", "user"),
                name="unique_approbation_user_proposition",
            ),
        ),
    ]
