# Generated by Django 4.1.7 on 2023-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poukidex", "0010_approbation_unique_approbation_user_proposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="index",
            name="object_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="publication",
            name="object_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
