# Generated by Django 4.1.7 on 2023-04-07 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("poukidex", "0014_collection_item_like_pendingitem_snap_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collection",
            name="unique_index_name",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="unique_publication_index_name",
        ),
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_approbation_user_proposition",
        ),
        migrations.RemoveConstraint(
            model_name="snap",
            name="unique_proposition_publication_user",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="approved",
            new_name="liked",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="validation_mode",
        ),
        migrations.AlterField(
            model_name="collection",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="poukidex.collection",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="snap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="poukidex.snap",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pendingitem",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_items",
                to="poukidex.collection",
            ),
        ),
        migrations.AlterField(
            model_name="pendingitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pendingitem",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pendingitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="snap",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snaps",
                to="poukidex.item",
            ),
        ),
        migrations.AlterField(
            model_name="snap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snaps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_collection_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("name", "collection"), name="unique_item_collection_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("snap", "user"), name="unique_like_user_snap"
            ),
        ),
        migrations.AddConstraint(
            model_name="snap",
            constraint=models.UniqueConstraint(
                fields=("item", "user"), name="unique_item_user"
            ),
        ),
    ]
